### ISSUE TITLE
Configuration File Location

### ISSUE THREAD

**Issue by anthropos9** [aftabnaveed/Sublime-DockerPHPUnit#1]
Could you please tell me where I'm supposed to put the configuration file? I've tried in the root of my app, in the vendor file, and even in the package itself. Nothing seems to work.  I've named the file: DockerPHPUnit.sublime-settings, so maybe that's the issue. Any help would be welcome. Thank you.

**Comment by aftabnaveed** [comment]
Hey, 

If you are using OSX or Windows you probably need to restart sublime for changes to take effect and it looks like the settings are only loaded from vendors folder at the moment. 

If you can share your console output that would make it easier to debug.

**Comment by anthropos9** [comment]
I tried restarting Sublime, no change.
Here is my vendor/DockerPHPUnit.sublime-settings file:
```
{
    "phpunit_path": "/var/www/gb2/vendor/bin/phpunit",
    "phpunit_xml_remote_path": "/var/www/gb2/phpunit.xml.dist",
    "docker_container": "php",
    "phpunit_xml_local_path": "phpunit.xml.dist"
}
```

Here is the output:

```Error: No such container: workspace
[Finished in 0.0s with exit code 1]
[cmd: docker exec workspace sh -c "/var/www/html/vendor/bin/phpunit -c /var/www/html/phpunit.xml"]
[dir: /Users/sdean/Sites/Project/projects/gb2]
[path: /Users/sdean/bin:/usr/local/php5/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:/Library/Frameworks/Mono.framework/Versions/Current/Commands]```

**Comment by aftabnaveed** [comment]
Hi there, 

Sorry for the confusion here, when I said vendor it should be something like this on windows

`C:\Users\your-user\AppData\Roaming\Sublime Text 3\Packages\Sublime-DockerPHPUnit`

Similarly, on OSX it should be somewhere in your home folder.
